name: SonarQube Analysis

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SonarQube Scan
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="${{ secrets.SONAR_HOST_URL }}" \
            -e SONAR_LOGIN="${{ secrets.SONAR_TOKEN }}" \
            -v "$(pwd):/usr/src" sonarsource/sonar-scanner-cli
